### ISSUE TITLE
Numbered list - No number showing

### ISSUE THREAD

**Issue by luis-apposha** [thomasreinecke/git-playbook#10]
I have tried using '1.' to make a numbered list but the numbers won't show.

**Comment by thomasreinecke** [comment]
known defect, I have no plans to fix this. If you find a solution, please let me know. Thank you

**Comment by luis-apposha** [comment]
Hi Thomas 
To show the numbered list just remove/comment line 124 of src/styles/_global.css where it says list-style: none; 
To maintain left alignment with the rest of the text, padding-left: 1.2em; can be added.
