### ISSUE TITLE
License or attribution?

### ISSUE THREAD

**Issue by jimschubert** [thomasreinecke/git-playbook#2]
@thomasreinecke I love the Git Playbook implementation. I don't see any attribution or licensing information in the project's current master, and I would like to at least add a "powered by" footer link. Do you have a preference for how to add this?

I currently have a PR open at OpenAPITools/openapi-generator#1614 which uses Git Playbook and [example output](https://jimschubert.github.io/openapi-generator).

**Comment by thomasreinecke** [comment]
Hi @jimschubert, I'm currently in the middle to sort this out. stay tuned

**Comment by BenLloydPearson** [comment]
Is there an update on this? This seems like a pretty neat project, but the lack of a license blocks me from using it.

**Comment by GadgetSteve** [comment]
Ditto Ben's comment above without a clear licence we cannot use this.

**Comment by jimschubert** [comment]
I decided to go with docusaurus. I'm leaving this open to track for others who still need clearly defined licensing.

**Comment by GadgetSteve** [comment]
@jimschubert [Docusaurus](https://github.com/facebook/docusaurus) does have nice clear licence information in it & we may have to go for it as well - it is a shame when promising projects like this one languish due to the author not including a clear licence.

**Comment by thomasreinecke** [comment]
put this project under MIT, apologies for the delay.
