### ISSUE TITLE
npm run build fails "Cannot find module .\Playbook\build\build.js" in Windows 10

### ISSUE THREAD

**Issue by lecniers** [thomasreinecke/git-playbook#3]
After doing a fresh clone of the repo in Windows 10, with current node versions 10.14.1 LTS and 11.3.0  the npm run build cmd fails with following messages:

PS C:\Users\lfreeman\testGitPlaybook> npm run build

> playbook@1.0.0 build C:\Users\lfreeman\testGitPlaybook
> node build/build.js; node build/build.search.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Users\lfreeman\testGitPlaybook\build\build.js;'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playbook@1.0.0 build: `node build/build.js; node build/build.search.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the playbook@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lfreeman\AppData\Roaming\npm-cache\_logs\2018-12-05T15_03_40_671Z-debug.log

**Comment by anywhichway** [comment]
I have the same issue

**Comment by anywhichway** [comment]
Interestingly if one types the build script commands directly at the command prompt they work, i.e. `node build/build.js`. Must be some environmental thing.

**Comment by anywhichway** [comment]
@lecniers try replacing `node build/build.js; node build/build.search.js` with `node build/build.js && node build/build.search.js`

**Comment by thomasreinecke** [comment]
thanks @anywhichway , updated package.json and pushed it. I cant test on windows. Assuming this fixes it, if not please reopen.
