### ISSUE TITLE
Error: Loading chunk 0 failed for content display

### ISSUE THREAD

**Issue by anywhichway** [thomasreinecke/git-playbook#5]
All the nav in your template project appears correctly when deployed to a prod site; however, the content areas do not. Below is the error.

```vue-router.esm.js:1905 Error: Loading chunk 0 failed.
    at HTMLScriptElement.r (bootstrap 0337016ea0a643c5e87a:103)
c @ vue-router.esm.js:1905
12:36:22.434```

**Comment by anywhichway** [comment]
See issue #1, there is still a reference to "/static" rather than "./static" that I have not found:

`https://anywhichway.github.io/static/js/0.1b0aa65053b39e77a660.js` should be `https://anywhichway.github.io/<sitename>/static/js/0.1b0aa65053b39e77a660.js`

**Comment by anywhichway** [comment]
Found a fix. Modified `config/index.js` to have the following settings:

```
 assetsSubDirectory: './static',
 assetsPublicPath: (process.env.GH_PAGES === 'true') ? '/git-playbook/' : '',
```

**Comment by thomasreinecke** [comment]
thanks @anywhichway - pushed this fix
