### ISSUE TITLE
ERROR - Resolved in ./src/pageConfig.json

### ISSUE THREAD

**Issue by christianmatei** [thomasreinecke/git-playbook#7]
Running npm build output with successful build:

ERROR in ./src/pageConfig.json
Module build failed: SyntaxError: Unexpected token { in JSON at position 2318
    at JSON.parse (<anonymous>)
    at Object.module.exports (C:\Users\blablabl_user_name\Desktop\git-playbook-master\node_modules\json-loader\index.js:3:49)
 @ ./src/services/configManager.js 3:0-44
 @ ./src/router/index.js
 @ ./src/main.js

In the file:
module.exports = function (source) {
  if (this.cacheable) this.cacheable();
  var value = typeof source === "string" ? JSON.parse(source) : source;
  value = JSON.stringify(value)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  return `module.exports = ${value}`;
}

RESOLVED by reinstalling

**Comment by christianmatei** [comment]
Resolved mine by reinstalling. Thank you so much.

**Comment by thomasreinecke** [comment]
you'll typically see this error when pageConfig.json isnt a valid JSON. the reason re-install resolved it was that pageConfig.json was reset by that. Next time make sure pageConfig.json is valid and you should be good too. Closing

**Comment by christianmatei** [comment]
Thank you so much. Great work on this.
