### ISSUE TITLE
Deploying playbook to GitHub enterprise shows blank screen when loading

### ISSUE THREAD

**Issue by tonykambo** [thomasreinecke/git-playbook#8]
Went through build setup instructions using unmodified code. Can execute 'npm run dev' and runs locally ok. Unit and e2e test failed with "playbook" <> "Git Playbook"  error message.
Can execute 'npm run gh-pages' but when attempting to load it shows a blank screen. Viewing page source shows it has loaded page with "This is your fallback content in case JavaScript fails to load". Repo named 'git-playbook'.

**Comment by thomasreinecke** [comment]
there is a hard-coded `git-playbook` reference in config/index.js which needs to be changed to your path. Please try that out. Thanks

![image](https://user-images.githubusercontent.com/35994116/59060072-8b04c000-88a0-11e9-8786-241e72b58db1.png)

**Comment by melona7** [comment]
I changed the path to be the name of my repository, but I am still having the same error. Could you clarify by what you mean by the path? Thanks.

**Comment by thomasreinecke** [comment]
e.g. this repo here runs on https://github.com/thomasreinecke/git-playbook, so the GH pages were deployed against https://thomasreinecke.github.io/git-playbook/#/playbook. The String on line 12 `git-playbook` needs to be changed to whatever your repo is (I assume you also try to deploy against GH pages, right?). This should do the trick

**Comment by xiuleiyy** [comment]
I am using GHE and also see the BLANK page issue. The resolution is change '/git-playbook/' to '/GHE-username/repo-name/'
